version: '3.7'
services:

       apache:
        build: './setup/apache'
        container_name: apache
        restart: always
        networks:
          - all
        depends_on:
          - php
        volumes:
          - ./public/:/var/www/html
        ports:
          - 80:80

       php:
        build: './setup/php'
        container_name: php
        restart: always
        networks:
          - all
        volumes:
          - ./public/:/var/www/html

networks:
  all:
